version: "3.8"
services:
  music_watcher:
    build: .
    container_name: music_watcher
    restart: unless-stopped
    environment:
      - WRAPAPI_KEY
    volumes:
      - /media/hd0/music/playlists/spotify:/app/music
      - /home/ha/playlists/mancanti:/app/mancanti
